--- #YAML:1.0
name:                Template-Timer
version:             1.00
abstract:            Rudimentary profiling for Template Toolkit
license:             ~
author:              
    - Andy Lester <andy@petdance.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Template:                      0
    Test::More:                    0
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
resources:
    license: http://dev.perl.org/licenses/
    Repository: http://github.com/petdance/template-timer/
