---
abstract: 'Rudimentary profiling for Template Toolkit'
author:
  - 'Andy Lester <andy@petdance.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120351'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Timer
no_index:
  directory:
    - t
    - inc
requires:
  Template: 0
  Test::More: 0
  Time::HiRes: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Template-Timer
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: https://github.com/petdance/template-timer
  x_MailingList: http://groups.google.com/group/ack-users
version: 1.01_01
